import {
  buildVaultPageAad as buildVaultPageAadImpl,
  canonicalPageAadJson,
  computeTitleSearchToken,
  decrypt as aeadDecrypt,
  deriveTitleSearchKey,
  encrypt as aeadEncrypt,
  ready,
  type VaultPageAadInput,
} from "@simplevault/crypto/browser";
import sodium from "libsodium-wrappers-sumo";

import { AAD_LABEL_VAULT_PAGE } from "./aad-labels";

/**
 * Phase 05 Plan 03 — browser-only encrypt/decrypt wrappers for vault page
 * blobs (TipTap JSON). High-level API: callers pass structured plaintext
 * and AAD-input params; this module serialises, builds AAD, derives
 * title-search token, and returns the full envelope.
 *
 * Sibling parity with `credential-cipher.ts`. The AAD label is imported
 * from `aad-labels.ts` (single source of truth; FINDING-0026 closure).
 */

/** Structured plaintext stored inside the encrypted blob. */
export interface DecryptedPagePlaintext {
  tiptapJson: unknown;
  isFavorite: boolean;
  meta: Record<string, unknown>;
}

/** Full envelope returned by `encryptPage` — includes everything the
 *  server needs to store (ciphertext+nonce) and index (aadParamsJson,
 *  titleSearchToken). */
export interface PageEnvelope {
  ciphertext: Uint8Array;
  nonce: Uint8Array;
  aadParamsJson: string;
  titleSearchToken: Uint8Array;
}

/** Convenience: build the per-page AAD using the label from `aad-labels.ts`. */
export function buildVaultPageAad(input: VaultPageAadInput): Uint8Array {
  return buildVaultPageAadImpl(input, AAD_LABEL_VAULT_PAGE);
}

/**
 * Encrypt a structured page plaintext under master_DEK. Builds AAD from
 * `aadInput`, derives the title-search token from the TipTap H1, and
 * returns the full `PageEnvelope`. The 24-byte nonce is generated by
 * `aead.encrypt` (libsodium `randombytes_buf`).
 */
export async function encryptPage(
  plaintext: DecryptedPagePlaintext,
  masterDek: Uint8Array,
  aadInput: { vaultId: string; pageId: string; version: number; email: string },
): Promise<PageEnvelope> {
  await ready();
  const aad = buildVaultPageAadImpl(
    { vaultId: aadInput.vaultId, pageId: aadInput.pageId, version: aadInput.version, email: aadInput.email },
    AAD_LABEL_VAULT_PAGE,
  );
  const pt = sodium.from_string(JSON.stringify(plaintext));
  const blob = await aeadEncrypt(pt, masterDek, aad);

  const aadParamsJson = canonicalPageAadJson({
    vaultId: aadInput.vaultId,
    pageId: aadInput.pageId,
    version: aadInput.version,
  });

  const titleSearchKey = await deriveTitleSearchKey(masterDek);
  const title = extractTitle(plaintext.tiptapJson);
  const titleSearchToken = await computeTitleSearchToken(
    titleSearchKey,
    title.trim().toLowerCase(),
  );

  return {
    ciphertext: blob.ciphertext,
    nonce: blob.nonce,
    aadParamsJson,
    titleSearchToken,
  };
}

/**
 * Decrypt a page envelope. Reconstructs the AAD from `blob.aadParamsJson`
 * (parsing out pageId, vaultId, version) combined with `opts.email`, then
 * decrypts and deserialises into `DecryptedPagePlaintext`. Throws on
 * AEAD tag mismatch (wrong key, tampered ciphertext, wrong AAD).
 */
export async function decryptPage(
  blob: { ciphertext: Uint8Array; nonce: Uint8Array; aadParamsJson: string },
  masterDek: Uint8Array,
  opts: { email: string },
): Promise<DecryptedPagePlaintext> {
  await ready();
  const params = JSON.parse(blob.aadParamsJson) as {
    pageId: string;
    vaultId: string;
    version: number;
  };
  const aad = buildVaultPageAadImpl(
    { vaultId: params.vaultId, pageId: params.pageId, version: params.version, email: opts.email },
    AAD_LABEL_VAULT_PAGE,
  );
  const pt = await aeadDecrypt({ ciphertext: blob.ciphertext, nonce: blob.nonce }, masterDek, aad);
  return JSON.parse(sodium.to_string(pt)) as DecryptedPagePlaintext;
}

interface TipTapTextNode {
  type: "text";
  text?: string;
}

interface TipTapHeadingNode {
  type: "heading";
  attrs?: { level?: number };
  content?: ReadonlyArray<TipTapTextNode | { type: string }>;
}

interface TipTapDoc {
  type?: string;
  content?: ReadonlyArray<unknown>;
}

function isTextNode(n: unknown): n is TipTapTextNode {
  return (
    typeof n === "object" &&
    n !== null &&
    (n as { type?: unknown }).type === "text"
  );
}

function isHeadingNode(n: unknown): n is TipTapHeadingNode {
  return (
    typeof n === "object" &&
    n !== null &&
    (n as { type?: unknown }).type === "heading"
  );
}

/**
 * Extracts the title from a TipTap doc: concatenated `text` content of
 * the FIRST `heading` node with `attrs.level === 1`. Returns `""` when no
 * such heading exists. Accepts either a parsed object or JSON string.
 */
export function extractTitle(tiptapJson: string | object | unknown): string {
  let doc: TipTapDoc;
  if (typeof tiptapJson === "string") {
    try {
      doc = JSON.parse(tiptapJson) as TipTapDoc;
    } catch {
      return "";
    }
  } else {
    doc = tiptapJson as TipTapDoc;
  }
  const content = doc?.content;
  if (!Array.isArray(content)) return "";
  for (const node of content) {
    if (!isHeadingNode(node)) continue;
    if (node.attrs?.level !== 1) continue;
    const children = node.content;
    if (!Array.isArray(children)) return "";
    let buf = "";
    for (const c of children) {
      if (isTextNode(c) && typeof c.text === "string") {
        buf += c.text;
      }
    }
    return buf;
  }
  return "";
}
