export const ErrorCodes = {
  // Auth (E1xxx)
  AUTH_INVALID_CREDENTIALS: "E1001",
  AUTH_2FA_REQUIRED: "E1002",
  AUTH_2FA_INVALID: "E1003",
  AUTH_SESSION_EXPIRED: "E1004",
  AUTH_REFRESH_REUSE_DETECTED: "E1005",
  AUTH_INVITE_INVALID: "E1006",
  AUTH_RATE_LIMITED: "E1007",

  // Vault (E2xxx)
  VAULT_NOT_FOUND: "E2001",
  VAULT_FORBIDDEN: "E2002",
  VAULT_QUOTA_EXCEEDED: "E2003",
  VAULT_INVITE_EXPIRED: "E2004",
  VAULT_DELETE_VOTE_DEADLOCK: "E2005",

  // Crypto (E3xxx)
  CRYPTO_DECRYPT_FAILED: "E3001",
  CRYPTO_KDF_DOWNGRADE_DETECTED: "E3002",
  CRYPTO_CHAIN_BREAK: "E3003",

  // Validation (E4xxx)
  VALIDATION_FAILED: "E4001",

  // Server (E5xxx)
  SERVER_INTERNAL: "E5001",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
